// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: connect/event/v1/event.proto

package eventv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/connect-sdk/event-api/proto/connect/event/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// EventServiceName is the fully-qualified name of the EventService service.
	EventServiceName = "connect.event.v1.EventService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventServicePushEventProcedure is the fully-qualified name of the EventService's PushEvent RPC.
	EventServicePushEventProcedure = "/connect.event.v1.EventService/PushEvent"
)

// EventServiceClient is a client for the connect.event.v1.EventService service.
type EventServiceClient interface {
	// PushEvent pushes a given event to cloud.event.v1.EventService service.
	PushEvent(context.Context, *connect.Request[v1.PushEventRequest]) (*connect.Response[v1.PushEventResponse], error)
}

// NewEventServiceClient constructs a client for the connect.event.v1.EventService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &eventServiceClient{
		pushEvent: connect.NewClient[v1.PushEventRequest, v1.PushEventResponse](
			httpClient,
			baseURL+EventServicePushEventProcedure,
			opts...,
		),
	}
}

// eventServiceClient implements EventServiceClient.
type eventServiceClient struct {
	pushEvent *connect.Client[v1.PushEventRequest, v1.PushEventResponse]
}

// PushEvent calls connect.event.v1.EventService.PushEvent.
func (c *eventServiceClient) PushEvent(ctx context.Context, req *connect.Request[v1.PushEventRequest]) (*connect.Response[v1.PushEventResponse], error) {
	return c.pushEvent.CallUnary(ctx, req)
}

// EventServiceHandler is an implementation of the connect.event.v1.EventService service.
type EventServiceHandler interface {
	// PushEvent pushes a given event to cloud.event.v1.EventService service.
	PushEvent(context.Context, *connect.Request[v1.PushEventRequest]) (*connect.Response[v1.PushEventResponse], error)
}

// NewEventServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventServiceHandler(svc EventServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventServicePushEventHandler := connect.NewUnaryHandler(
		EventServicePushEventProcedure,
		svc.PushEvent,
		opts...,
	)
	return "/connect.event.v1.EventService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventServicePushEventProcedure:
			eventServicePushEventHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventServiceHandler struct{}

func (UnimplementedEventServiceHandler) PushEvent(context.Context, *connect.Request[v1.PushEventRequest]) (*connect.Response[v1.PushEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("connect.event.v1.EventService.PushEvent is not implemented"))
}
